### ISSUE TITLE
[Question] 您好，在cuda10下运行模型，报错Fail to find the dnn implementation.谢谢

### ISSUE THREAD

**Issue by wyqnumber** [BrikerMan/Kashgari#168]
Epoch 1/20
2019-07-19 10:34:06.768267: I tensorflow/stream_executor/dso_loader.cc:152] successfully opened CUDA library libcublas.so.10.0 locally
2019-07-19 10:34:07.669769: E tensorflow/stream_executor/cuda/cuda_dnn.cc:334] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-07-19 10:34:07.669826: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at cudnn_rnn_ops.cc:1217 : Unknown: Fail to find the dnn implementation.
2019-07-19 10:34:07.680118: E tensorflow/stream_executor/cuda/cuda_dnn.cc:334] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-07-19 10:34:07.680151: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at cudnn_rnn_ops.cc:1217 : Unknown: Fail to find the dnn implementation.
Traceback (most recent call last):
  File "/home/wyq/PycharmProjects/MyProject/201907/Practice/kashgari/ner.py", line 32, in <module>
    batch_size=2)
  File "/home/wyq/Public/SoftWare/anaconda3/lib/python3.6/site-packages/kashgari_tf-0.5.1-py3.6.egg/kashgari/tasks/base_model.py", line 295, in fit
  File "/home/wyq/Public/SoftWare/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1426, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/wyq/Public/SoftWare/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_generator.py", line 191, in model_iteration
    batch_outs = batch_function(*batch_data)
  File "/home/wyq/Public/SoftWare/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1191, in train_on_batch
    outputs = self._fit_function(ins)  # pylint: disable=not-callable
  File "/home/wyq/Public/SoftWare/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/backend.py", line 3076, in __call__
    run_metadata=self.run_metadata)
  File "/home/wyq/Public/SoftWare/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1439, in __call__
    run_metadata_ptr)
  File "/home/wyq/Public/SoftWare/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.UnknownError: Fail to find the dnn implementation.
	 [[{{node layer_blstm/CudnnRNN}}]]
	 [[{{node layer_crf/rnn/while/Switch_1}}]]

**Comment by BrikerMan** [comment]
请按照 issue 模板提供一下系统信息，软件版本，关键代码。
