### ISSUE TITLE
ValueError: if reps is tensor.vector, you should specify the ndim

### ISSUE THREAD

**Issue by snakecy** [BrikerMan/Kashgari#2]

**Comment by BrikerMan** [comment]
Please provide more details, sample code, etc...

**Comment by snakecy** [comment]
when using "
embedding = BERTEmbedding('/home/yy/classify_demo/chinese_L-12_H-768_A-12/',30)"
the error :
Traceback (most recent call last):
  File "own_train.py", line 29, in <module>
    embedding = BERTEmbedding('/home/yy/temp_work/ner_test/classification_task/chinese_classify_demo/chinese_L-12_H-768_A-12/',30)
  File "/home/yy/py36_venv/lib/python3.6/site-packages/kashgari/embeddings/embeddings.py", line 69, in __init__
    self.build(**kwargs)
  File "/home/yy/py36_venv/lib/python3.6/site-packages/kashgari/embeddings/embeddings.py", line 288, in build
    seq_len=self.sequence_length)
  File "/home/yy/py36_venv/lib/python3.6/site-packages/keras_bert/loader.py", line 36, in load_trained_model_from_checkpoint
    training=training,
  File "/home/yy/py36_venv/lib/python3.6/site-packages/keras_bert/bert.py", line 65, in get_model
    trainable=training,
  File "/home/yy/py36_venv/lib/python3.6/site-packages/keras_bert/layers/embedding.py", line 56, in get_embedding
    )(embed_layer)
  File "/home/yy/py36_venv/lib/python3.6/site-packages/keras/engine/base_layer.py", line 457, in __call__
    output = self.call(inputs, **kwargs)
  File "/home/yy/py36_venv/lib/python3.6/site-packages/keras_pos_embd/pos_embd.py", line 130, in call
    K.stack([batch_size, 1, 1]),
  File "/home/yy/py36_venv/lib/python3.6/site-packages/keras/backend/theano_backend.py", line 1055, in tile
    y = T.tile(x, n)
  File "/home/yy/py36_venv/lib/python3.6/site-packages/theano/tensor/basic.py", line 5434, in tile
    raise ValueError("if reps is tensor.vector, you should specify "
ValueError: if reps is tensor.vector, you should specify the ndim

**Comment by BrikerMan** [comment]
are you using theano as Keras backend? I only tested this project with tensorflow, maybe you should try to use tensorflow backend.

**Comment by snakecy** [comment]
i install tensorflow, but it requried "ModuleNotFoundError: No module named 'theano'"

**Comment by BrikerMan** [comment]
Please provide the complete error message.

**Comment by snakecy** [comment]
the script as following:

from kashgari.tasks.classification import CNNModel
from kashgari.embeddings import BERTEmbedding
from kashgari.tasks.classification import CNNLSTMModel
from kashgari.embeddings import WordEmbeddings

# init embedding
# embedding = BERTEmbedding('bert-base-chinese', sequence_length=30)
# or init embedding by embedding file path
embedding = BERTEmbedding('/home/yy/classify_demo/chinese_L-12_H-768_A-12/',30)

def read_file(path):
    lines = open(path, 'r', encoding='utf-8').read().splitlines()
    x_list = []
    y_list = []
    for line in tqdm.tqdm(lines):
        rows = line.split('\t')
        if len(rows) >= 2:
            y_list.append(rows[0])
            x_list.append(list(jieba.cut('\t'.join(rows[1:]))))
        else:
            print(rows)
    return x_list, y_list

test_x, test_y = read_file('titlenews/test.txt')
train_x, train_y = read_file('titlenews/train.txt')
val_x, val_y = read_file('titlenews/val.txt')

#embedding = WordEmbeddings('sgns.weibo.bigram', sequence_length=30) 
#embedding = WordEmbeddings('/home/yy/classify_demo/news_12g_baidubaike_20g_novel_90g_embedding_64.bin', 30, limit=1000) 
#model = CNNLSTMModel(embedding)
model = CNNModel(embedding)
#model = CNNModel()
model.fit(train_x, train_y, val_x, val_y, batch_size=128)
model.evaluate(test_x, test_y)
model.save('./titlemodel')

the first error:
Traceback (most recent call last):
  File "own_train.py", line 3, in <module>
    from kashgari.tasks.classification import CNNModel
  File "/home/yy/py36_venv/lib/python3.6/site-packages/kashgari/__init__.py", line 13, in <module>
    import kashgari.embeddings
  File "/home/yy/py36_venv/lib/python3.6/site-packages/kashgari/embeddings/__init__.py", line 13, in <module>
    from .embeddings import BERTEmbedding
  File "/home/yy/py36_venv/lib/python3.6/site-packages/kashgari/embeddings/embeddings.py", line 18, in <module>
    import keras_bert
  File "/home/yy/py36_venv/lib/python3.6/site-packages/keras_bert/__init__.py", line 1, in <module>
    from .bert import gelu, get_model, get_custom_objects, get_base_dict, gen_batch_inputs
  File "/home/yy/py36_venv/lib/python3.6/site-packages/keras_bert/bert.py", line 2, in <module>
    import keras
ModuleNotFoundError: No module named 'keras'


after install keras:
then
  File "/home/yy/py36_venv/lib/python3.6/site-packages/keras/backend/theano_backend.py", line 7, in <module>
    import theano
ModuleNotFoundError: No module named 'theano'


after install theano:
the error turns out as the title.

**Comment by BrikerMan** [comment]
please create a new virtualenv, then install 
```
pip install kashgari==0.1.5
pip install tensorflow
```
then run your code~

**Comment by snakecy** [comment]
still reqired the theano....so crazy.....

**Comment by BrikerMan** [comment]
So problem solved by changing backend to tensorflow at `~/.keras/keras.json` ?

**Comment by snakecy** [comment]
> So problem solved by changing backend to tensorflow at `~/.keras/keras.json` ?

yes, it likes as:
```
{
    "image_dim_ordering": "tf",
    "epsilon": 1e-07,
    "floatx": "float32",
    "backend": "tensorflow"
}
```
by changing image_dim_ordering as tf, backend as tensorflow.  

if using theano, then ,
by changing image_dim_ordering as th, backend as theano.
