### ISSUE TITLE
[BUG] AttributeError: 'list' object has no attribute 'argmax'

### ISSUE THREAD

**Issue by echan00** [BrikerMan/Kashgari#221]
I am running into an error with `evaluation` function relating to the `argmax` attribute for a sequence labeling model

Tensorflow 1.14.0
kashgari-tf 0.5.1

```
model = BiLSTM_Model(bert_embedding)
model.fit(train_x, train_y, valid_x, valid_y, epochs=10)
model.evaluate(test_x, test_y, debug_info=True)
```

```
Total params: 180,232,198
Trainable params: 3,280,390
Non-trainable params: 176,951,808
__________________________________________________________________________________________________
Epoch 1/10
W0830 13:06:12.186806 140698843129600 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/math_grad.py:1250: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
2019-08-30 13:06:14.326478: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10.0
2019-08-30 13:06:14.921455: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
156/156 [==============================] - 88s 567ms/step - loss: 0.1708 - acc: 0.9313 - val_loss: 0.1217 - val_acc: 0.9492
Epoch 2/10
156/156 [==============================] - 85s 544ms/step - loss: 0.1275 - acc: 0.9468 - val_loss: 0.1143 - val_acc: 0.9527
Epoch 3/10
156/156 [==============================] - 85s 544ms/step - loss: 0.1216 - acc: 0.9495 - val_loss: 0.1146 - val_acc: 0.9517
Epoch 4/10
156/156 [==============================] - 85s 546ms/step - loss: 0.1169 - acc: 0.9517 - val_loss: 0.1090 - val_acc: 0.9553
Epoch 5/10
156/156 [==============================] - 85s 545ms/step - loss: 0.1131 - acc: 0.9533 - val_loss: 0.1056 - val_acc: 0.9571
Epoch 6/10
156/156 [==============================] - 85s 544ms/step - loss: 0.1094 - acc: 0.9549 - val_loss: 0.1045 - val_acc: 0.9569
Epoch 7/10
156/156 [==============================] - 85s 543ms/step - loss: 0.1062 - acc: 0.9562 - val_loss: 0.1020 - val_acc: 0.9580
Epoch 8/10
156/156 [==============================] - 85s 543ms/step - loss: 0.1029 - acc: 0.9576 - val_loss: 0.0990 - val_acc: 0.9590
Epoch 9/10
156/156 [==============================] - 85s 545ms/step - loss: 0.1003 - acc: 0.9590 - val_loss: 0.0984 - val_acc: 0.9593
Epoch 10/10
156/156 [==============================] - 85s 544ms/step - loss: 0.0968 - acc: 0.9606 - val_loss: 0.0951 - val_acc: 0.9619

Traceback (most recent call last):
  File "process.py", line 165, in <module>
    model.evaluate(test_x, test_y, debug_info=True)
  File "/usr/local/lib/python3.6/dist-packages/kashgari/tasks/labeling/base_model.py", line 95, in evaluate
    y_pred = self.predict(x_data, batch_size=batch_size)
  File "/usr/local/lib/python3.6/dist-packages/kashgari/tasks/base_model.py", line 401, in predict
    res = self.embedding.reverse_numerize_label_sequences(pred.argmax(-1),
AttributeError: 'list' object has no attribute 'argmax'
```

**Comment by echan00** [comment]
Problem was due to empty test_x & test_y
