### ISSUE TITLE
[Question] Loading BiGRU_CRF Model

### ISSUE THREAD

**Issue by echan00** [BrikerMan/Kashgari#226]
I don't have any problems loading a BiLSTM_CRF_Model:
`model = kashgari.utils.load_model('BiLSTM_CRF_Model_20')`

But loading a BiGRU_CRF_Model seems to not work:

```
model = kashgari.utils.load_model('BiGRU_CRF_Model_30')

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/kashgari/utils.py", line 64, in load_model
    model.tf_model.load_weights(os.path.join(model_path, 'model_weights.h5'))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py", line 162, in load_weights
    return super(Model, self).load_weights(filepath, by_name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/network.py", line 1424, in load_weights
    saving.load_weights_from_hdf5_group(f, self.layers)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/hdf5_format.py", line 749, in load_weights_from_hdf5_group
    layer, weight_values, original_keras_version, original_backend)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/hdf5_format.py", line 370, in preprocess_weights_for_loading
    weights = convert_nested_bidirectional(weights)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/hdf5_format.py", line 308, in convert_nested_bidirectional
    original_keras_version, original_backend)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/hdf5_format.py", line 461, in preprocess_weights_for_loading
    return _convert_rnn_weights(layer, weights)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/hdf5_format.py", line 622, in _convert_rnn_weights
    raise ValueError('%s is not compatible with %s' % types)
ValueError: CuDNNGRU is not compatible with GRU(reset_after=False)
```

Is this expected?

**Comment by BrikerMan** [comment]
This is an issue with CuDNN Cells, and fixed in 0.5.3 version. Just update and train again. See more details https://github.com/BrikerMan/Kashgari/issues/198.
