### ISSUE TITLE
[Question]  AttributeError: 'NoneType' object has no attribute 'process_x_dataset'

### ISSUE THREAD

**Issue by echan00** [BrikerMan/Kashgari#227]
I'm trying to load a model with a stacked embedding (bert and numeric). It seems like the embedding does not exist on load.

```
>>>  model = kashgari.utils.load_model('BiLSTM_CRF_Model2_10')
>>> model.predict(test[0])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/kashgari/tasks/base_model.py", line 399, in predict
    tensor = self.embedding.process_x_dataset(x_data)
AttributeError: 'NoneType' object has no attribute 'process_x_dataset'
```

I also tried the following to return the embedding of the loaded model and it is empty:
```
>>> model.embedding
<blank>
```

**Comment by echan00** [comment]
I see this under utils.py:

```
    embedding: Embedding = embed_class._load_saved_instance(embed_info,
                                                            model_path,
                                                            model.tf_model)
    model.embedding = embedding
```

Should it actually be the following?

```
    embedding: Embedding = embed_class._load_saved_instance(embed_info,
                                                            model_path,
                                                            model.tf_model)
    model.embedding = Embedding
```

I tried it but receiving a different type of error now:
```
>>> model.embedding.process_x_dataset(test_x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: process_x_dataset() missing 1 required positional argument: 'data'
```
