### ISSUE TITLE
Error using the simple code provided in the doc. How to solve it?

### ISSUE THREAD

**Issue by urvishp80** [BrikerMan/Kashgari#278]
I am trying out this library for the first time and I am facing a lot of trouble in doing transfer-learning in NLP. Here is my code I am using

```from kashgari.embeddings import BERTEmbedding
from kashgari.tasks.labeling import BiGRU_Model
from kashgari.corpus import ChineseDailyNerCorpus
import kashgari
import numpy as np

import os
cwd = os.getcwd()

# print(os.path.join(cwd, 'uncased_L-12_H-768_A-12'))
kashgari.config.use_cudnn_cell = True
bert_embedding = BERTEmbedding(os.path.join(cwd, 'uncased_L-12_H-768_A-12/'), sequence_length=100,
                               task=kashgari.CLASSIFICATION)
model = BiGRU_Model(bert_embedding)

from kashgari.corpus import SMP2018ECDTCorpus
train_x, train_y = SMP2018ECDTCorpus.load_data('train')
valid_x, valid_y = SMP2018ECDTCorpus.load_data('valid')
test_x, test_y = SMP2018ECDTCorpus.load_data('test')

model.fit(train_x, train_y, valid_x, valid_y)
```

More or less it is copied from the docs and still not runnig properly. Here is the error I am getting 

```Traceback (most recent call last):
  File "bert_kashgari.py", line 21, in <module>
    model.fit(train_x, train_y, valid_x, valid_y)
  File "C:\Users\Urvish\Envs\tf_1_14\lib\site-packages\kashgari\tasks\base_model.py", line 310, in fit
    **fit_kwargs)
  File "C:\Users\Urvish\Envs\tf_1_14\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1433, in fit_generator
    steps_name='steps_per_epoch')
  File "C:\Users\Urvish\Envs\tf_1_14\lib\site-packages\tensorflow\python\keras\engine\training_generator.py", line 264, in model_iteration
    batch_outs = batch_function(*batch_data)
  File "C:\Users\Urvish\Envs\tf_1_14\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1153, in train_on_batch
    extract_tensors_from_dataset=True)
  File "C:\Users\Urvish\Envs\tf_1_14\lib\site-packages\tensorflow\python\keras\engine\training.py", line 2692, in _standardize_user_data
    y, self._feed_loss_fns, feed_output_shapes)
  File "C:\Users\Urvish\Envs\tf_1_14\lib\site-packages\tensorflow\python\keras\engine\training_utils.py", line 549, in check_loss_and_target_compatibility
    ' while using as loss `' + loss_name + '`. '
ValueError: A target array with shape (64, 31) was passed for output of shape (None, 100, 31) while using as loss `categorical_crossentropy`. This loss expects targets to have the same shape as the output.```

Before this, I was trying something similar with `ChineseDailyNerCorpus` data and I was getting this error
```Traceback (most recent call last):
  File "bert_kashgari.py", line 20, in <module>
    model.fit(np.asarray(train_x), np.asarray(train_y))
  File "C:\Users\Urvish\Envs\tf_1_14\lib\site-packages\kashgari\tasks\base_model.py", line 278, in fit
    self.build_model(x_train, y_train, x_validate, y_validate)
  File "C:\Users\Urvish\Envs\tf_1_14\lib\site-packages\kashgari\tasks\base_model.py", line 130, in build_model
    self.embedding.analyze_corpus(x_train, y_train)
  File "C:\Users\Urvish\Envs\tf_1_14\lib\site-packages\kashgari\embeddings\bert_embedding.py", line 143, in analyze_corpus
    super(BERTEmbedding, self).analyze_corpus(x, y)
  File "C:\Users\Urvish\Envs\tf_1_14\lib\site-packages\kashgari\embeddings\base_embedding.py", line 148, in analyze_corpus
    self.processor.analyze_corpus(x, y)
  File "C:\Users\Urvish\Envs\tf_1_14\lib\site-packages\kashgari\processors\base_processor.py", line 77, in analyze_corpus
    self._build_label_dict(labels)
  File "C:\Users\Urvish\Envs\tf_1_14\lib\site-packages\kashgari\processors\classification_processor.py", line 35, in _build_label_dict
    label_set = set(labels)
TypeError: unhashable type: 'list'
```

What is wrong here in the code? Also can you guys update the `readme` with the links to the `BERT` embedding and `GPT2` embedding this way user can have a lot of help in getting started?

**Comment by urvishp80** [comment]
I used the code from the documentation which has full explanation about on how to use the BERT embeddings.

**Comment by BrikerMan** [comment]
You are using SMP2018ECDTCorpus data instead of ChineseDailyNerCorpus. You need to use labeling corpus with labeling task.
