### ISSUE TITLE
请教关于WordEmbedding的问题

### ISSUE THREAD

**Issue by vrocker2048** [BrikerMan/Kashgari#339]
## Environment

- tf:1.14.0
- Python Version:3.6.5
- requirements.txt:

```txt
[Paste requirements.txt file here]
```

## Question
本人小白，在测试WordEmbedding方法的时候，按照文档说明写了下面代码。w2v_path参数是word2cec 300d的bin文件。

```
embedding = WordEmbedding(
                          w2v_path=WORD_EMBED_PATH,
                          task=kashgari.CLASSIFICATION,
                          w2v_kwargs={'binary': True},
                          sequence_length=50
                          )

model = BiLSTM_Model(embedding=embedding)
```

为什么在加载的时候总是报错，错误信息如下

```
WARNING: Logging before flag parsing goes to stderr.
W0313 20:30:12.686193  3100 macros.py:36] CUDA GPU available, you can set `kashgari.config.use_cudnn_cell = True` to use CuDNNCell. This will speed up the training, but will make model incompatible with CPU device.
W0313 20:30:16.043576  3100 smart_open_lib.py:385] this function is deprecated, use smart_open.open instead
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1356, in _do_call
    return fn(*args)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InternalError: Dst tensor is not initialized.
	 [[{{node ReadVariableOp}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:/code/first_try.py", line 60, in <module>
    sequence_length=5
  File "C:\Anaconda3\lib\site-packages\kashgari\embeddings\word_embedding.py", line 69, in __init__
    self._build_model()
  File "C:\Anaconda3\lib\site-packages\kashgari\embeddings\word_embedding.py", line 115, in _build_model
    embedded_tensor = layer_embedding(input_tensor)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 688, in __call__
    self.set_weights(self._initial_weights)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 1121, in set_weights
    backend.batch_set_value(weight_value_tuples)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\keras\backend.py", line 3071, in batch_set_value
    get_session().run(assign_ops, feed_dict=feed_dict)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 950, in run
    run_metadata_ptr)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1350, in _do_run
    run_metadata)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Dst tensor is not initialized.
	 [[node ReadVariableOp (defined at C:\Anaconda3\lib\site-packages\kashgari\embeddings\word_embedding.py:115) ]]

Original stack trace for 'ReadVariableOp':
  File "F:/code/first_try.py", line 60, in <module>
    sequence_length=5
  File "C:\Anaconda3\lib\site-packages\kashgari\embeddings\word_embedding.py", line 69, in __init__
    self._build_model()
  File "C:\Anaconda3\lib\site-packages\kashgari\embeddings\word_embedding.py", line 115, in _build_model
    embedded_tensor = layer_embedding(input_tensor)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 688, in __call__
    self.set_weights(self._initial_weights)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 1121, in set_weights
    backend.batch_set_value(weight_value_tuples)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\keras\backend.py", line 3066, in batch_set_value
    assign_op = x.assign(assign_placeholder)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 1145, in assign
    return self._lazy_read(assign_op)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 1119, in _lazy_read
    parent_op=op, unique_id=self._unique_id)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\ops\variables.py", line 263, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 1552, in __init__
    self._graph_element = self.read_value()
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 1566, in read_value
    return self._read_variable_op()
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 1571, in _read_variable_op
    self._dtype)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_resource_variable_ops.py", line 587, in read_variable_op
    "ReadVariableOp", resource=resource, dtype=dtype, name=name)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3616, in create_op
    op_def=op_def)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()
```
换了维度更小的词向量，换了不同的机器也还是这个问题
请问这是哪里出错了呢。没有查到相关的资料，恳请大佬解答！万分感谢

**Comment by shaojiangnie** [comment]
我也有相同的问题，请问最后怎么解决的？

**Comment by vrocker2048** [comment]
> 我也有相同的问题，请问最后怎么解决的？

emmm...
我最后是直接减少word2vec或者glove的词表大小
