### ISSUE TITLE
[BUG] 使用bert embedding v2训练完，加载模型时报错

### ISSUE THREAD

**Issue by yaleimeng** [BrikerMan/Kashgari#358]
## Check List
- [x] I have searched in [existing issues](https://github.com/BrikerMan/Kashgari/issues?utf8=%E2%9C%93&q=is%3Aissue+) but did not find the same one.
- [x] I have read the [documents](https://kashgari.bmio.net)

## Environment
- OS [e.g. Mac OS, Linux]: Ubuntu 18.04
- Python Version:  3.6.8
- requirements.txt:

###  先是使用bert embedding v2加载Electra模型训练NER任务。直到保存模型都正常。
后来加载模型进行预测时报错。报错信息如下
Traceback (most recent call last):
  File "/home/……/newkash/example.py", line 90, in <module>
    model = kashgari.utils.load_model('./model')
  File "/home/……kash/lib/python3.6/site-packages/kashgari/utils.py", line 67, in load_model
    model.tf_model = tf.keras.models.model_from_json(model_json_str, custom_objects)
  File "/home/……kash/lib/python3.6/site-packages/tensorflow/python/keras/saving/model_config.py", line 96, in model_from_json
    return deserialize(config, custom_objects=custom_objects)
  File "/home/……kash/lib/python3.6/site-packages/tensorflow/python/keras/layers/serialization.py", line 89, in deserialize
    printable_module_name='layer')
  File "/home/……kash/lib/python3.6/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 192, in deserialize_keras_object
    list(custom_objects.items())))
  File "/home/……kash/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 1121, in from_config
    process_layer(layer_data)
  File "/home/……kash/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 1105, in process_layer
    layer = deserialize_layer(layer_data, custom_objects=custom_objects)
  File "/home/……kash/lib/python3.6/site-packages/tensorflow/python/keras/layers/serialization.py", line 89, in deserialize
    printable_module_name='layer')
  File "/home/……kash/lib/python3.6/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 194, in deserialize_keras_object
    return cls.from_config(cls_config)
  File "/home/……kash/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 446, in from_config
    return cls(**config)
  File "/home/……kash/lib/python3.6/site-packages/keras_pos_embd/pos_embd.py", line 65, in __init__
    super(PositionEmbedding, self).__init__(**kwargs)
  File "/home/……kash/lib/python3.6/site-packages/tensorflow/python/training/tracking/base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/home/……kash/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 157, in __init__
    generic_utils.validate_kwargs(kwargs, allowed_kwargs)
  File "/home/……kash/lib/python3.6/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 600, in validate_kwargs
    raise TypeError(error_message, kwarg)
TypeError: ('Keyword argument not understood:', 'merge_mode')

### Reproduce
出错由 kashgari.utils.load_model('./model')引发，涉及到  tf.keras.models.model_from_json(model_json_str, custom_objects) 中的 custom_objects。在处理一些自定义层的时候出现问题。

### Other Comment
使用Ellectra Base\small，甚至Google官方格式的中文albert都有同样的问题。这应该是一个涉及bert embedding v2兼容模型时一个普遍的问题。

**Comment by BrikerMan** [comment]
Try this:

```python
# Add three lines of code for fixing the custom object issue
import kashgari
from bert4keras.layers import custom_objects
kashgari.custom_objects.update(custom_objects)

# then load the model
model = kashgari.utils.load_model('./model')
```

**Comment by yaleimeng** [comment]
多谢指点，问题解决。

**Comment by dongrixinyu** [comment]
@BrikerMan 大佬您好
我也遇到了相同的问题：添加自定义层后，无法加载模型。而且，添加上述三行代码后仍无法解决，依然报错。

自定义层结构：
```
class BahdanauAttention(tf.keras.Model):
    def __init__(self, units, class_num):
        super(BahdanauAttention, self).__init__()
        self.W1 = L.Dense(units)
        self.W2 = list()
        for i in range(class_num):
            self.W2.append(
                L.Dense(1, activation='sigmoid', 
                activity_regularizer=tf.keras.regularizers.l2(l=l2_coefficient)))
            
        self.V = L.Dense(1)
        self.class_num = class_num  # 类别的数量
        #'''
        self.query = self.add_weight(
            name='query', shape=(self.class_num, units,), 
            initializer=tf.constant_initializer(0.1), 
            dtype='float32', trainable=True)  
        # '''
    
    def get_config(self):
        return None
    
    def call(self, values):
        class_tensor_list = list()  # 存放每个类别的值
        class_att_weights_list = list()  # 存放每个类别的注意力权重，仅用于查看
        for idx, class_dense_layer in enumerate(self.W2):
            query = self.query[idx,:]
            score = self.V(tf.nn.tanh(
                self.W1(values) + query))

            attention_weights = tf.nn.softmax(score, axis=1)
            #print(attention_weights)
            context_vector = attention_weights * values
            #print(values)
            #print(context_vector)
            context_vector = tf.reduce_sum(context_vector, axis=1)
            #pdb.set_trace()
            class_scalar = class_dense_layer(context_vector)
            class_tensor_list.append(class_scalar)
            class_att_weights_list.append(attention_weights)
            #print(context_vector)
        context_vector = tf.concat(class_tensor_list, axis=-1)
        attention_weights = tf.concat(class_att_weights_list, axis=-1)
        return context_vector, attention_weights
```
报错信息：
```

Traceback (most recent call last):
  File "predict.py", line 49, in <module>
    loaded_model = kashgari.utils.load_model('ccks_event_model_bert_small')
  File "/data3/ml/cuichengyu/Kashgari/kashgari/utils.py", line 75, in load_model
    model.tf_model = _custom_load_keras_model_from_json(model_json_str)
  File "/data3/ml/cuichengyu/Kashgari/kashgari/utils.py", line 109, in _custom_load_keras_model_from_json
    pdb.set_trace()
  File "/data3/ml/cuichengyu/Kashgari/kashgari/utils.py", line 109, in _custom_load_keras_model_from_json
    pdb.set_trace()
  File "/data3/ml/cuichengyu/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/keras/saving/model_config.py", line 96, in model_from_json
    return deserialize(config, custom_objects=custom_objects)
  File "/data3/ml/cuichengyu/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/keras/layers/serialization.py", line 89, in deserialize
    printable_module_name='layer')
  File "/data3/ml/cuichengyu/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 192, in deserialize_keras_object
    list(custom_objects.items())))
  File "/data3/ml/cuichengyu/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 1123, in from_config
    process_layer(layer_data)
  File "/data3/ml/cuichengyu/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 1107, in process_layer
    layer = deserialize_layer(layer_data, custom_objects=custom_objects)
  File "/data3/ml/cuichengyu/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/keras/layers/serialization.py", line 89, in deserialize
    printable_module_name='layer')
  File "/data3/ml/cuichengyu/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 194, in deserialize_keras_object
    return cls.from_config(cls_config)
  File "/data3/ml/cuichengyu/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 446, in from_config
    return cls(**config)
  File "/data3/ml/cuichengyu/anaconda3/envs/py36/lib/python3.6/site-packages/keras_layer_normalization/layer_normalization.py", line 33, in __init__
    super(LayerNormalization, self).__init__(**kwargs)
  File "/data3/ml/cuichengyu/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/training/tracking/base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/data3/ml/cuichengyu/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 157, in __init__
    generic_utils.validate_kwargs(kwargs, allowed_kwargs)
  File "/data3/ml/cuichengyu/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 600, in validate_kwargs
    raise TypeError(error_message, kwarg)
TypeError: ('Keyword argument not understood:', 'axis')
```
其中，keras 版本均为 2.2.4-1
