### ISSUE TITLE
[BUG] 多标签文本分类报错

### ISSUE THREAD

**Issue by dongrixinyu** [BrikerMan/Kashgari#368]
**You must follow the issue template and provide as much information as possible. otherwise, this issue will be closed.
请按照 issue 模板要求填写信息。如果没有按照 issue 模板填写，将会忽略并关闭这个 issue**
## Check List

Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.

**You can post pictures, but if specific text or code is required to reproduce the issue, please provide the text in a plain text format for easy copy/paste.**

- [ ] I have searched in [existing issues](https://github.com/BrikerMan/Kashgari/issues?utf8=%E2%9C%93&q=is%3Aissue+) but did not find the same one.
- [ ] I have read the [documents](https://kashgari.bmio.net)

## Environment

- Linux:16.04
- Python Version: 3.6
- requirements.txt: 均按 Kashgari 安装。

```txt
[Paste requirements.txt file here]
```

### What

多标签文本分类，在训练第一轮过程中成功，在第一轮完成后，evaluate 阶段报错。

文件 ：   Kashgari/kashgari/tasks/classification/base_model.py
第70~76行：这里 tensor 包含两部分，一部分是 input_idx，另一部分是全0 的输入。
```
            tensor = self.embedding.process_x_dataset(x_data)
            pdb.set_trace()
            pred = self.tf_model.predict(tensor, batch_size=batch_size)
            print(self.embedding.processor.multi_label)
            if self.embedding.processor.multi_label:
                if debug_info:
                    logging.info('raw output: {}'.format(pred))
                print(pred)
                pdb.set_trace()
                pred[pred >= multi_label_threshold] = 1
                pred[pred < multi_label_threshold] = 0
```

打印 pred 结果为 :

```
array([[nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       ...,
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan]], dtype=float16)
```
而在训练过程是正常的，可以看到损失函数为 15 左右。
```
 1/10 [==>...........................] - ETA: 1:06 - loss: 15.3750 - acc: 0.9644512 30
 2/10 [=====>........................] - ETA: 39s - loss: 15.3750 - acc: 0.9648 512 30
 3/10 [========>.....................] - ETA: 28s - loss: 15.3802 - acc: 0.9648512 30
 4/10 [===========>..................] - ETA: 22s - loss: 15.3828 - acc: 0.9648512 30
 5/10 [==============>...............] - ETA: 17s - loss: 15.3844 - acc: 0.9648512 30
 6/10 [=================>............] - ETA: 13s - loss: 15.3841 - acc: 0.9648512 30
 7/10 [====================>.........] - ETA: 9s - loss: 15.3850 - acc: 0.9648 512 30
 8/10 [=======================>......] - ETA: 6s - loss: 15.3857 - acc: 0.9648392 30
 9/10 [==========================>...] - ETA: 3s - loss: 15.3863 - acc: 0.9653512 30

```

### 我的使用代码：

```

import kashgari

kashgari.config.use_cudnn_cell = True
kashgari.config.disable_auto_summary = True

from tensorflow.python import keras
from kashgari.embeddings import BERTEmbedding
from kashgari.callbacks import EvalCallBack
from tensorflow.keras.callbacks import ReduceLROnPlateau, ModelCheckpoint
from kashgari.tasks.classification import BiLSTM_Model 
from kashgari.processors import ClassificationProcessor 
from kashgari.embeddings import BareEmbedding


# 参数集合
sequence_length = 100



logging.basicConfig(level='DEBUG')  
processor = ClassificationProcessor(multi_label=True) 

bert_embed = BERTEmbedding(
    '/data3/ml/cuichengyu/bert_ner/pretrained_models/bert_tiny',
    task=kashgari.CLASSIFICATION,
    processor=processor,
    sequence_length=sequence_length)

hyper = BiLSTM_Model.get_default_hyper_parameters()
model = BiLSTM_Model(bert_embed, hyper_parameters=hyper)

train_x = train_x[:5000]
train_y = train_y[:5000]

model.build_model(train_x, train_y, valid_x, valid_y)

#for idx, i in enumerate(model.tf_model.layers[:24]):  
#    # 指仅保留最后一层 encoder 可finetune，外加 bigru 作为可训练参数，默认 49，
#    print(idx, i)
#    i.trainable = False

optimizer = tf.keras.optimizers.Adam(lr=1e-4)
model.compile_model(loss='binary_crossentropy', #'categorical_crossentropy', 
                    optimizer=optimizer, 
                    metrics=['accuracy'])



reduse_lr_callback = ReduceLROnPlateau(factor=0.1, patience=5)
tf_board_callback = keras.callbacks.TensorBoard(
    log_dir='./logs', update_freq=1000)
eval_callback = EvalCallBack(
    kash_model=model, valid_x=valid_x, valid_y=valid_y, 
    batch_size=512, step=1)

model.fit(train_x, train_y,
          x_validate=valid_x, 
          y_validate=valid_y,
          epochs=10, batch_size=512,
          callbacks=[tf_board_callback, 
                     eval_callback])

```
输入数据格式为：
```
train_x = ['2019年3月25日?-?多赢金融的运营主体为深圳市前海多赢金融服务有限公司,深扒其股权结构,发现...2019-04-051帮友贷平台无法提现多日已经公布清盘,准备跑路的前奏2019-...']
train_y = [['歇业停业', '提现困难']]

```

### Other Comment
怀疑是 callback 里不支持 多标签分类。

**Comment by BrikerMan** [comment]
如果去掉 callback 还会报错么？
还要需要提供 kashgari 版本~

**Comment by dongrixinyu** [comment]
版本 
tensorflow==1.14
kashgari==1.1.5。
去掉 callback 之后 ，运行是成功的，但是新的问题来了。

- 这是一个多标签分类任务，类别总共有30个。
- 损失函数选择的是 binary_crossentropy， 如上代码所示。
在我 evaluate 阶段，我打印了其中的 一条数据的值，结果是如下：

```
(Pdb) pred[0]
array([0.31305957, 0.03524877, 0.04333559, 0.01896148, 0.0136203 ,
       0.05087354, 0.07379142, 0.00318011, 0.01021451, 0.00926139,
       0.01353562, 0.02509246, 0.00275897, 0.00758954, 0.01096897,
       0.00479162, 0.01326395, 0.0849857 , 0.03095625, 0.02632303,
       0.08622839, 0.02491677, 0.01765032, 0.02155102, 0.00752297,
       0.01991595, 0.00941971, 0.00909734, 0.00720569, 0.00467907],
      dtype=float32)
(Pdb) sum(pred[0])
1.0000000298023224

```
- 其它的样本结果类似。可以看出，它并没有按照多标签分类的方式来计算，它的和还是约等于 1。这是有问题的。它的运行结果还是多分类的 交叉熵的样子。

**Comment by BrikerMan** [comment]
可以通过 `model.tf_model.to_yaml()` 看看最后一个层的激活函数，应该是 `sigmoid`，看看是不是配置成 `softmax`。

**Comment by dongrixinyu** [comment]
是的，是 softmax
```
  - class_name: Dense
    config:
      activation: softmax
      activity_regularizer: null
      bias_constraint: null
      bias_initializer:
        class_name: Zeros


```

**Comment by BrikerMan** [comment]
那应该确实是 bug，我这边修复一下~

**Comment by dongrixinyu** [comment]
好像也不是源码的问题

也就是 hyper 那里的默认参数需要匹配一下就可以了。
```
hyper['layer_dense']['activation'] = 'sigmoid'  #
```
```
(Pdb) pred[0]
array([0.28025314, 0.04294947, 0.06403834, 0.03142157, 0.04419798,
       0.07920548, 0.05211905, 0.01879421, 0.03445411, 0.01990694,
       0.05351955, 0.03005213, 0.0205158 , 0.02441031, 0.02966106,
       0.0352442 , 0.02380782, 0.02641138, 0.02888703, 0.02210411,
       0.06095165, 0.04182026, 0.03733918, 0.03160581, 0.02020931,
       0.01193312, 0.01828286, 0.013217  , 0.03799573, 0.01993513],
      dtype=float32)
(Pdb) sum(pred[0])
1.255243718624115
```

**Comment by BrikerMan** [comment]
应该在选择 multi-label 时候，默认使用 sigmoid

**Comment by BrikerMan** [comment]
@dongrixinyu tf2 版本也正在测试多标签分类，可以的话测试一下~

文档连接 https://kashgari.readthedocs.io/en/kashgari2/tutorial/text-classification.html#multi-label-classification

**Comment by dongrixinyu** [comment]
好的，我目前没有安装 tf2 呢，等我测试了给你说

**Comment by dongrixinyu** [comment]
@BrikerMan 已测试，成功的。

**Comment by dongrixinyu** [comment]
又出现一个非常无语的错误，应该是 tensorflow 的问题：

我在自定义模型里加了一句：
```
...
dropout_tensor = tf.reduce_mean(embed_model.output, axis=1, name='reduce_layer')
...

```

就加上这一句后，模型训练完全正常，但是在模型保存时爆出了：
```
Traceback (most recent call last):
  File "train_bert.py", line 285, in <module>
    model.save('ccks_subject_model_bert_small')
  File "/data3/ml/cuichengyu/Kashgari/kashgari/tasks/base_model.py", line 466, in save
    f.write(json.dumps(self.info(), indent=2, ensure_ascii=True))
  File "/data3/ml/cuichengyu/Kashgari/kashgari/tasks/base_model.py", line 39, in info
    model_json_str = self.tf_model.to_json()
  File "/data3/ml/cuichengyu/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 1458, in to_json
    model_config, default=serialization.get_json_type, **kwargs)
  File "/data3/ml/cuichengyu/anaconda3/envs/py36/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/data3/ml/cuichengyu/anaconda3/envs/py36/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/data3/ml/cuichengyu/anaconda3/envs/py36/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/data3/ml/cuichengyu/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/util/serialization.py", line 69, in get_json_type
    raise TypeError('Not JSON Serializable:', obj)
TypeError: ('Not JSON Serializable:', b'\n\x0creduce_layer\x12\x04Mean\x1a,non_masking_layer/non_masking_layer/Identity\x1a\x1ereduce_layer/reduction_indices*\x07\n\x01T\x12\x020\x01*\x0f\n\tkeep_dims\x12\x02(\x00*\n\n\x04Tidx\x12\x020\x03')

```

去掉这个操作后就没事了。不知道是为什么

**Comment by dongrixinyu** [comment]
@BrikerMan 我自定义的一个模型，Costume，训练完成，保存起来。然后加载预测，报错：
```
> /data3/ml/cuichengyu/Kashgari/kashgari/utils.py(68)load_model()
-> model = model_class()
(Pdb) l
 63  	        model_info = json.load(f)
 64  	
 65  	    model_class = pydoc.locate(f"{model_info['module']}.{model_info['class_name']}")
 66  	    model_json_str = json.dumps(model_info['tf_model'])
 67  	    pdb.set_trace()
 68  ->	    model = model_class()
 69  	
 70  	    # Fix loading bug caused by custom objects naming duplication in keras_bert and bert4keras
 71  	    custom_obj_1 = kashgari.custom_objects
 72  	    custom_obj_2 = dict(custom_obj_1)
 73  	    custom_obj_2.update(keras_bert.get_custom_objects())
(Pdb) model_class()
*** TypeError: 'NoneType' object is not callable

```

如上，可以看出工具包不能找到模型代码的位置

**Comment by BrikerMan** [comment]
在 load 之前试试 import 这个 Model~

**Comment by sly123197811** [comment]
> 那应该确实是 bug，我这边修复一下~

您好，我最近在做多标签分类时，训练时准确率很快到达90以上，loss也很小，但是测试时，准确率都为0，请问可能是哪里出了问题，请指教，我在另一个帖子里面详细说明了，希望您指点一下，谢谢
