### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [BrikerMan/Kashgari#373]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 0.5.5. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary kashgari-tf -w /tmp/ext kashgari-tf==0.5.5
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting kashgari-tf==0.5.5
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/c9a/5be9d197fb74c/kashgari-tf-0.5.5.tar.gz (41 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-h0lvqvya/kashgari-tf/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-h0lvqvya/kashgari-tf/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-h0lvqvya/kashgari-tf/pip-egg-info
         cwd: /tmp/pip-wheel-h0lvqvya/kashgari-tf/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-h0lvqvya/kashgari-tf/setup.py", line 55, in <module>
        with codecs.open('requirements.txt', 'r', 'utf8') as reader:
      File "/usr/lib/python3.8/codecs.py", line 905, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by BrikerMan** [comment]
Just try the latest version~ 

```
pip install kashgari
```

**Comment by BrikerMan** [comment]
I am curious about the use-case. Is that ok to share more details with me?

**Comment by thatch** [comment]
Some companies and distros want to compile everything from source, so pass `--no-binary :all:`, for example https://github.com/dropbox/dbx_build_tools/blob/master/build_tools/py/vpip.py#L311

**Comment by BrikerMan** [comment]
Thanks for the explanation. Never run into this issue before.
