### ISSUE TITLE
[Question] 无法导入

### ISSUE THREAD

**Issue by cdhx** [BrikerMan/Kashgari#427]
## Environment

- OS [e.g. Mac OS, Linux]:Window10
- Python Version:3.7

## Question
pip install kashgari后
导入import kashgari报错
Traceback (most recent call last):

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *

ImportError: DLL load failed while importing _pywrap_tensorflow_internal: 找不到指定的模块。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "<ipython-input-177-336bb98816f4>", line 1, in <module>
    import kashgari

  File "C:\ProgramData\Anaconda3\lib\site-packages\kashgari\__init__.py", line 24, in <module>
    from kashgari import layers

  File "C:\ProgramData\Anaconda3\lib\site-packages\kashgari\layers\__init__.py", line 11, in <module>
    from tensorflow import keras

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\__init__.py", line 40, in <module>
    from tensorflow.python.eager import context

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\eager\context.py", line 35, in <module>
    from tensorflow.python import pywrap_tfe

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tfe.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 83, in <module>
    raise ImportError(msg)

ImportError: Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: 找不到指定的模块。

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by cdhx** [comment]
尝试安装2.0以下版本
```pip install "kashgari>=1.1,<2.0"```
报错
```
ERROR: Command errored out with exit status 1: 'C:\ProgramData\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Dell\\AppData\\Local\\Temp\\pip-install-d8a_g65p\\numpy\\setup.py'"'"'; __file__='"'"'C:\\Users\\Dell\\AppData\\Local\\Temp\\pip-install-d8a_g65p\\numpy\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Dell\AppData\Local\Temp\pip-record-dyxcgozc\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\ProgramData\Anaconda3\Include\numpy' Check the logs for full command output.
```

**Comment by BrikerMan** [comment]
这个似乎是 tensorflow 的问题....

```
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: 找不到指定的模块。
``

**Comment by cdhx** [comment]
是tf版本问题
tf和kashgari都安装不上
发现是因为这个电脑的版本是py38
