### ISSUE TITLE
[Question] 文本分类例子导入模块报错

### ISSUE THREAD

**Issue by Xw-Jia** [BrikerMan/Kashgari#71]
尝试例子的时候，这两句都会报错：
#from kashgari.embeddings import BERTEmbedding

from kashgari.tasks.classification import CNNModel

#embedding = BERTEmbedding('/home/xwjia/bert-base-chinese', sequence_length=400)

Traceback (most recent call last):

  File "/home/xwjia/.virtualenvs/bert_venv/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-10-fdbc1b194a18>", line 2, in <module>
    from kashgari.tasks.classification import CNNModel

  File "/home/xwjia/.virtualenvs/bert_venv/lib/python3.5/site-packages/kashgari/__init__.py", line 13, in <module>
    import kashgari.embeddings

  File "/home/xwjia/.virtualenvs/bert_venv/lib/python3.5/site-packages/kashgari/embeddings/__init__.py", line 13, in <module>
    from .embeddings import BERTEmbedding

  File "/home/xwjia/.virtualenvs/bert_venv/lib/python3.5/site-packages/kashgari/embeddings/embeddings.py", line 65
    self._token2idx: Dict[str, int] = None
                   ^
SyntaxError: invalid syntax
定位到这里，实在不知道怎么解决，求翻牌。谢谢。

**Comment by BrikerMan** [comment]
项目最低要求 Python 3.6，3.5 的话会报错。
