### ISSUE TITLE
卸载TensorFlow-1.11.0后，只安装tensorflow-gpu (1.11.0)训练报错

### ISSUE THREAD

**Issue by chros425** [BrikerMan/Kashgari#8]
Using TensorFlow backend.
Traceback (most recent call last):
  File "train.py", line 235, in <module>
    from kashgari.embeddings import BERTEmbedding
  File "/data1/chh/software/anaconda3/lib/python3.6/site-packages/kashgari/__init__.py", line 13, in <module>
    import kashgari.embeddings
  File "/data1/chh/software/anaconda3/lib/python3.6/site-packages/kashgari/embeddings/__init__.py", line 13, in <module>
    from .embeddings import BERTEmbedding
  File "/data1/chh/software/anaconda3/lib/python3.6/site-packages/kashgari/embeddings/embeddings.py", line 18, in <module>
    import keras_bert
  File "/data1/chh/software/anaconda3/lib/python3.6/site-packages/keras_bert/__init__.py", line 1, in <module>
    from .bert import gelu, get_model, get_custom_objects, get_base_dict, gen_batch_inputs
  File "/data1/chh/software/anaconda3/lib/python3.6/site-packages/keras_bert/bert.py", line 2, in <module>
    import keras
  File "/data1/chh/software/anaconda3/lib/python3.6/site-packages/keras/__init__.py", line 3, in <module>
    from . import utils
  File "/data1/chh/software/anaconda3/lib/python3.6/site-packages/keras/utils/__init__.py", line 6, in <module>
    from . import conv_utils
  File "/data1/chh/software/anaconda3/lib/python3.6/site-packages/keras/utils/conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "/data1/chh/software/anaconda3/lib/python3.6/site-packages/keras/backend/__init__.py", line 89, in <module>
    from .tensorflow_backend import *
  File "/data1/chh/software/anaconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 6, in <module>
    from tensorflow.python.framework import ops as tf_ops
ModuleNotFoundError: No module named 'tensorflow.python'

**Comment by chros425** [comment]
我使用的是Keras (2.2.4)，python3.6.4、kashgari (0.1.6)、keras-bert (0.29.0)
