### ISSUE TITLE
导入bert模型时发现错误，from kashgari.embeddings import BERTEmbedding

### ISSUE THREAD

**Issue by luruixuan** [BrikerMan/Kashgari#97]
A clear and concise description of what you want to know.
Traceback (most recent call last):
  File "diedai2.py", line 186, in <module>
    from kashgari.embeddings import BERTEmbedding
  File "/usr/local/lib/python3.5/dist-packages/kashgari/__init__.py", line 13, in <module>
    import kashgari.embeddings
  File "/usr/local/lib/python3.5/dist-packages/kashgari/embeddings/__init__.py", line 13, in <module>
    from .embeddings import BERTEmbedding
  File "/usr/local/lib/python3.5/dist-packages/kashgari/embeddings/embeddings.py", line 70
    self._token2idx: Dict[str, int] = None

**Comment by BrikerMan** [comment]
Use `Python 3.6+`
